# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edf83f78096108a6093e693f6fa273c5d36a7fb78fd150d2c30720e365a0fc4019f54c01414d09a20075bc0fa40112c7c3af46825b6c309b5962e4f34431df03

test:
  secret_key_base: 8f70a9aa6c1390095c6cf13bd1bd2087597478270d5accc534e9ae7abac30311d52d620d11e00765fdbb2b28dd80b69598e4f86f4b2fd005453b1458b3a50e20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
